include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - test/**.mocks.dart
    - lib/generated_plugin_registrant.dart
  strong-mode:
    implicit-casts: false

linter:
  rules:
    prefer_relative_imports: true
    always_use_package_imports: false