name: twitch_api
description: A wrapper in pure Dart to connect to Twitch.tv using OAuth implicit authentication.
version: 0.0.1
author: Guillaume Roux
homepage: https://github.com/TesteurManiak/twitch_api_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10

dev_dependencies:
  test: ^1.15.4
